from ..pattern import PAbs as pabs
from ..pattern import PAdd as padd
from ..pattern import PAnd as pand
from ..pattern import PArpeggiator as parp
from ..pattern import PArrayIndex as parrayindex
from ..pattern import PBinOp as pbinop
from ..pattern import PBrown as pbrown
from ..pattern import PChanged as pchanged
from ..pattern import PChoice as pchoice
from ..pattern import PCoin as pcoin
from ..pattern import PCollapse as pcollapse
from ..pattern import PConcatenate as pconcatenate
from ..pattern import PConstant as pconstant
from ..pattern import PCounter as pcounter
from ..pattern import PCreep as pcreep
from ..pattern import PCurrentTime as pcurrenttime
from ..pattern import PDecisionPoint as pdecisionpoint
from ..pattern import PDegree as pdegree
from ..pattern import PDict as pdict
from ..pattern import PDictKey as pdictkey
from ..pattern import PDiff as pdiff
from ..pattern import PDiv as pdiv
from ..pattern import PEqual as pequal
from ..pattern import PEuclidean as peuclidean
from ..pattern import PExplorer as pexplorer
from ..pattern import PFade as pfade
from ..pattern import PFadeNotewise as pfadenotewise
from ..pattern import PFadeNotewiseRandom as pfadenotewiserandom
from ..pattern import PFilterByKey as pfilterbykey
from ..pattern import PFlipFlop as pflipflop
from ..pattern import PFloorDiv as pfloordiv
from ..pattern import PFunc as pfunc
from ..pattern import PGeom as pgeom
from ..pattern import PGlobals as pglobals
from ..pattern import PGreaterThan as pgreaterthan
from ..pattern import PGreaterThanOrEqual as pgreaterthanorequal
from ..pattern import PImpulse as pimpulse
from ..pattern import PIndexOf as pindexof
from ..pattern import PInt as pint
from ..pattern import PInterpolate as pinterpolate
from ..pattern import PLShift as plshift
from ..pattern import PLSystem as plsystem
from ..pattern import PLessThan as plessthan
from ..pattern import PLessThanOrEqual as plessthanorequal
from ..pattern import PLoop as ploop
from ..pattern import PMIDIControl as pmidicontrol
from ..pattern import PMap as pmap
from ..pattern import PMapEnumerated as pmapenumerated
from ..pattern import PMarkov as pmarkov
from ..pattern import PMetropolis as pmetropolis
from ..pattern import PMidiNoteToFrequency as pnotetofreq
from ..pattern import PMidiSemitonesToFrequencyRatio as psemistofreq
from ..pattern import PMod as pmod
from ..pattern import PMul as pmul
from ..pattern import PNearestNoteInKey as pnearestnote
from ..pattern import PNoRepeats as pnorepeats
from ..pattern import PNormalise as pnormalise
from ..pattern import PNotEqual as pnotequal
from ..pattern import PPad as ppad
from ..pattern import PPadToMultiple as ppadtomultiple
from ..pattern import PPatternGeneratorAction as ppatterngeneratoraction
from ..pattern import PPermut as ppermut
from ..pattern import PPingPong as ppingpong
from ..pattern import PPow as ppow
from ..pattern import PRShift as prshift
from ..pattern import PRandomExponential as prandexp
from ..pattern import PRandomImpulseSequence as prandimpseq
from ..pattern import PRandomWalk as prandomwalk
from ..pattern import PRange as prange
from ..pattern import PRef as pref
from ..pattern import PReset as preset
from ..pattern import PReverse as preverse
from ..pattern import PRound as pround
from ..pattern import PSample as psample
from ..pattern import PSaw as psaw
from ..pattern import PScalar as pscalar
from ..pattern import PScaleLinExp as pscalelinexp
from ..pattern import PScaleLinLin as pscalelinlin
from ..pattern import PSeq as pseq
from ..pattern import PSequence as pseq
from ..pattern import PSequenceAction as psequenceaction
from ..pattern import PSeries as pseries
from ..pattern import PShuffle as pshuffle
from ..pattern import PShuffleInput as pshuffleinput
from ..pattern import PSkip as pskip
from ..pattern import PSkipIf as pskipif
from ..pattern import PStaticPattern as pstaticpattern
from ..pattern import PStochasticPattern as pstochasticpattern
from ..pattern import PStutter as pstutter
from ..pattern import PSub as psub
from ..pattern import PSubsequence as psubsequence
from ..pattern import PSwitchOne as pswitchone
from ..pattern import PTri as ptri
from ..pattern import PWInterpolate as pwinterpolate
from ..pattern import PWRallantando as pwrallantando
from ..pattern import PWSine as pwsine
from ..pattern import PWarp as pwarp
from ..pattern import PWhite as pwhite
from ..pattern import PWrap as pwrap